using System;
using System.Collections.Generic;

namespace BusinessLayer
{
    public class Student1
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public int Age { get; set; }
    }
    public  class StudentData1:IStudent
    {
        public  List<Student1> GetStudents()
        {
            return new List<Student1>() {
        new Student1() { StudentID = 1, StudentName = "John", Age = 13} ,
        new Student1() { StudentID = 2, StudentName = "Moin",  Age = 21 } ,
        new Student1() { StudentID = 3, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 4, StudentName = "Ram" , Age = 20} ,
        new Student1() { StudentID = 5, StudentName = "Ron" , Age = 15 },
        new Student1() { StudentID = 6, StudentName = "Karan", Age = 30} ,
        new Student1() { StudentID = 7, StudentName = "Priyanka",  Age = 32 } ,
        new Student1() { StudentID = 8, StudentName = "Kiran",  Age = 29 } ,
        new Student1() { StudentID = 9, StudentName = "Ramesh" , Age = 50} ,
        new Student1() { StudentID = 10, StudentName = "Ronnie" , Age = 40 },
        new Student1() { StudentID = 11, StudentName = "Jerry", Age = 23} ,
        new Student1() { StudentID = 12, StudentName = "Mohan",  Age = 28 } ,
        new Student1() { StudentID = 13, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 14, StudentName = "Vikas" , Age = 17} ,
        new Student1() { StudentID = 15, StudentName = "Tarun" , Age = 16 },
         new Student1() { StudentID = 16, StudentName = "John", Age = 13} ,
        new Student1() { StudentID = 17, StudentName = "Moin",  Age = 21 } ,
        new Student1() { StudentID = 18, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 19, StudentName = "Ram" , Age = 20} ,
        new Student1() { StudentID = 20, StudentName = "Ron" , Age = 15 },
        new Student1() { StudentID = 21, StudentName = "Karan", Age = 30} ,
        new Student1() { StudentID = 22, StudentName = "Priyanka",  Age = 32 } ,
        new Student1() { StudentID = 23, StudentName = "Kiran",  Age = 29 } ,
        new Student1() { StudentID = 24, StudentName = "Ramesh" , Age = 50} ,
        new Student1() { StudentID = 25, StudentName = "Ronnie" , Age = 40 },
        new Student1() { StudentID = 26, StudentName = "Jerry", Age = 23} ,
        new Student1() { StudentID = 27, StudentName = "Mohan",  Age = 28 } ,
        new Student1() { StudentID = 28, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 29, StudentName = "Vikas" , Age = 17} ,
        new Student1() { StudentID = 30, StudentName = "Tarun" , Age = 16 },
         new Student1() { StudentID = 31, StudentName = "John", Age = 13} ,
        new Student1() { StudentID = 32, StudentName = "Moin",  Age = 21 } ,
        new Student1() { StudentID = 33, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 34, StudentName = "Ram" , Age = 20} ,
        new Student1() { StudentID = 35, StudentName = "Ron" , Age = 15 },
        new Student1() { StudentID = 36, StudentName = "Karan", Age = 30} ,
        new Student1() { StudentID = 37, StudentName = "Priyanka",  Age = 32 } ,
        new Student1() { StudentID = 38, StudentName = "Kiran",  Age = 29 } ,
        new Student1() { StudentID = 39, StudentName = "Ramesh" , Age = 50} ,
        new Student1() { StudentID = 40, StudentName = "Ronnie" , Age = 40 },
        new Student1() { StudentID = 41, StudentName = "Jerry", Age = 23} ,
        new Student1() { StudentID = 42, StudentName = "Mohan",  Age = 28 } ,
        new Student1() { StudentID = 43, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 44, StudentName = "Vikas" , Age = 17} ,
        new Student1() { StudentID = 45, StudentName = "Tarun" , Age = 16 },
         new Student1() { StudentID = 46, StudentName = "John", Age = 13} ,
        new Student1() { StudentID = 47, StudentName = "Moin",  Age = 21 } ,
        new Student1() { StudentID = 48, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 49, StudentName = "Ram" , Age = 20} ,
        new Student1() { StudentID = 50, StudentName = "Ron" , Age = 15 },
        new Student1() { StudentID = 6, StudentName = "Karan", Age = 30} ,
        new Student1() { StudentID = 7, StudentName = "Priyanka",  Age = 32 } ,
        new Student1() { StudentID = 8, StudentName = "Kiran",  Age = 29 } ,
        new Student1() { StudentID = 9, StudentName = "Ramesh" , Age = 50} ,
        new Student1() { StudentID = 10, StudentName = "Ronnie" , Age = 40 },
        new Student1() { StudentID = 11, StudentName = "Jerry", Age = 23} ,
        new Student1() { StudentID = 12, StudentName = "Mohan",  Age = 28 } ,
        new Student1() { StudentID = 13, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 14, StudentName = "Vikas" , Age = 17} ,
        new Student1() { StudentID = 15, StudentName = "Tarun" , Age = 16 },
         new Student1() { StudentID = 1, StudentName = "John", Age = 13} ,
        new Student1() { StudentID = 2, StudentName = "Moin",  Age = 21 } ,
        new Student1() { StudentID = 3, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 4, StudentName = "Ram" , Age = 20} ,
        new Student1() { StudentID = 5, StudentName = "Ron" , Age = 15 },
        new Student1() { StudentID = 6, StudentName = "Karan", Age = 30} ,
        new Student1() { StudentID = 7, StudentName = "Priyanka",  Age = 32 } ,
        new Student1() { StudentID = 8, StudentName = "Kiran",  Age = 29 } ,
        new Student1() { StudentID = 9, StudentName = "Ramesh" , Age = 50} ,
        new Student1() { StudentID = 10, StudentName = "Ronnie" , Age = 40 },
        new Student1() { StudentID = 11, StudentName = "Jerry", Age = 23} ,
        new Student1() { StudentID = 12, StudentName = "Mohan",  Age = 28 } ,
        new Student1() { StudentID = 13, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 14, StudentName = "Vikas" , Age = 17} ,
        new Student1() { StudentID = 15, StudentName = "Tarun" , Age = 16 },
         new Student1() { StudentID = 1, StudentName = "John", Age = 13} ,
        new Student1() { StudentID = 2, StudentName = "Moin",  Age = 21 } ,
        new Student1() { StudentID = 3, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 4, StudentName = "Ram" , Age = 20} ,
        new Student1() { StudentID = 5, StudentName = "Ron" , Age = 15 },
        new Student1() { StudentID = 6, StudentName = "Karan", Age = 30} ,
        new Student1() { StudentID = 7, StudentName = "Priyanka",  Age = 32 } ,
        new Student1() { StudentID = 8, StudentName = "Kiran",  Age = 29 } ,
        new Student1() { StudentID = 9, StudentName = "Ramesh" , Age = 50} ,
        new Student1() { StudentID = 10, StudentName = "Ronnie" , Age = 40 },
        new Student1() { StudentID = 11, StudentName = "Jerry", Age = 23} ,
        new Student1() { StudentID = 12, StudentName = "Mohan",  Age = 28 } ,
        new Student1() { StudentID = 13, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 14, StudentName = "Vikas" , Age = 17} ,
        new Student1() { StudentID = 15, StudentName = "Tarun" , Age = 16 },
         new Student1() { StudentID = 1, StudentName = "John", Age = 13} ,
        new Student1() { StudentID = 2, StudentName = "Moin",  Age = 21 } ,
        new Student1() { StudentID = 3, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 4, StudentName = "Ram" , Age = 20} ,
        new Student1() { StudentID = 5, StudentName = "Ron" , Age = 15 },
        new Student1() { StudentID = 6, StudentName = "Karan", Age = 30} ,
        new Student1() { StudentID = 7, StudentName = "Priyanka",  Age = 32 } ,
        new Student1() { StudentID = 8, StudentName = "Kiran",  Age = 29 } ,
        new Student1() { StudentID = 9, StudentName = "Ramesh" , Age = 50} ,
        new Student1() { StudentID = 10, StudentName = "Ronnie" , Age = 40 },
        new Student1() { StudentID = 11, StudentName = "Jerry", Age = 23} ,
        new Student1() { StudentID = 12, StudentName = "Mohan",  Age = 28 } ,
        new Student1() { StudentID = 13, StudentName = "Bill",  Age = 18 } ,
        new Student1() { StudentID = 14, StudentName = "Vikas" , Age = 17} ,
        new Student1() { StudentID = 15, StudentName = "Tarun" , Age = 16 }
        };
    }
 }


}
